### ISSUE TITLE
20230104 Chap.13

### ISSUE THREAD

**Issue by hyeriful** [data-tech-newbie/Kubernetes_In_Action#13]
# Chap.13 클러스터 노드와 네트워크 보안

- 파드가 노드의 리소스에 액세스할 수 있게 하는 법
- 파드에서 사용자가 원하는 작업을 마음대로 수행할 수 없도록 클러스터를 구성하는 방법
- 파드가 통신할 때 사용하는 네트워크를 보호하는 방법

## 파드에서 노드의 기본 리눅스 네임스페이스 사용

`hostNetwork: true`로 설정한 파드는 파드 네트워크 인터페이스 대신 노드 네트워크 인터페이스를 사용한다.
(파드 매니페스트에서 `spec.hostNetwork: true`로 설정하면 된다.)

![13-1](https://user-images.githubusercontent.com/55703132/210229640-14cc6dcf-3aa0-47e6-b7ca-b7fd1bbdaf24.jpeg)

그러나 hostport 사용은 하지말고, NodePort를 사용하자.

> Don't specify a hostPort for a Pod unless it is absolutely necessary.
...<중략>...
If you explicitly need to expose a Pod's port on the node, consider using a NodePort Service before resorting to hostPort.
> 
> ref. [kubernetes docs](https://kubernetes.io/docs/concepts/configuration/overview/#services)

<img alt="NodePort" width=650 src="https://user-images.githubusercontent.com/55703132/210789616-5e0a9d35-89c0-476f-99c6-df0d78f65c79.png" />

```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-app
```

## 컨테이너의 보안 컨텍스트 구성

Dockerfile에 USER 지시문으로 지정된 사용자로 컨테이너가 실행된다. 생략하면 컨테이너는 루트로 실행된다.
(* 루트로 프로세스를 실행하는 것은 나쁜 관행)

- 컨테이너를 특정 사용자로 실행
`securityContext.runAsUser` 속성을 지정하면 된다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-as-user-guest
spec:
  containers:
  - name: main
     securityContext:
       runAsUser: 405
```

```sh
$ kubectl exec pod-as-user-guest id
uid=405(guest) gid=100(users)
```

- 컨테이너가 루트로 실행되는 것 방지
`securityContext.runAsNonRoot: true`로 설정한다. 그러면 이 컨테이너는 루트가 아닌 사용자로만 실행할 수 있다.

- 특권 모드에서 파드 실행
노드 커널의 모든 액세스 권한을 얻기 위해 파드의 컨테이너를 privileged mode로 실행할 때,
`securityContext.privileged: true`로 설정한다.

때때로 파드는 일반 컨테이너에서는 접근할 수 없는 보호된 시스템 장치나
'커널의 다른 기능을 사용하는 것'과 같이 그들이 실행 중인 노드가 할 수 있는 모든 것을 해야할 수도 있다. (e.g. kube-proxy 파드)

\* root와의 차이점?
privileged가 root보다 사용가능한 Linux capabilities가 많은듯? ([참고한 글](https://itnext.io/docker-and-kubernetes-root-vs-privileged-9d2a37453dec))
> the container access to almost everything the host can do.

root로 실행하는 것을 비추천하듯, privileged mode로 실행하는 것도 비추천.

- 컨테이너에서 기능 제거
`securityContext.capabilities:drop` 속성 아래에 제거할 기능을 적는다.

- 프로세스가 컨테이너의 파일시스템에 쓰는 것 방지
`securityContext.readOnlyRootFilesystem: true`
컨테이너에서 실행 중인 프로세스가 컨테이너의 파일시스템에 쓰지 못하게 하고 마운트된 볼륨에만 쓰도록 할 수 있다.
대부분 보안상의 이유로 이 작업이 필요하다.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readonly-filesystem
spec:
  containers:
  - name: main
     images: alpine
     command: ["/bin/sleep", "999999"]
     securityContext:
       readOnlyRootFilesystem: true
     volumeMounts:
     - name: my-volume
       mountPath: /volume
       readOnly: false
  volumnes:
  - name: my-bolume
    empthDir:
```

- 컨테이너가 다른 사용자로 실행될 때 볼륨 공유
두 개의 컨테이너를 두 명의 다른 사용자로 실행해야 할 수도 있는데, 이때 두 컨테이너가 볼륨으로 파일을 공유하는 경우 반드시 서로의 파일을 읽거나 쓸 수 있는 것은 아니다.
`fsGroup`, `supplementalGroups` 속성을 지정하여 실행 중인 사용자 ID에 상관없이 파일을 공유할 수 있다.
\* fsGroup, supplementalGroups는 **파드 레벨**의 보안 컨텍스트에서 정의된다.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-shared-volume-fsgroup
spec:
  securityContext:
     fsGroup: 555
     supplementalGroups: [666, 777]
  containers:
  - name: first
     images: alpine
     command: ["/bin/sleep", "999999"]
     securityContext:
       runAsUser: 111
     volumeMounts:
     - name: shared-volume
       mountPath: /volume
       readOnly: false
  - name: second
     images: alpine
     command: ["/bin/sleep", "999999"]
     securityContext:
       runAsUser: 222
     volumeMounts:
     - name: shared-volume
       mountPath: /volume
       readOnly: false
  volumnes:
  - name: shared-volume
    empthDir:
```

일반적으로 사용자의 유효 그룹 ID는 사용자가 파일을 만들 때 사용된다. (파일을 만들었을 때 그룹ID 확인하는 예제는 p.586-587에서 확인가능)
fsGroup 보안 컨텍스트 속성은 프로세스가 볼륨에 파일을 생성할 때 사용되고,
supplementalGroups 속성은 사용자와 관련된 추가 그룹 ID 목록을 정의하는데 사용된다.

## 파드의 보안 관련 기능 사용 제한

클러스터 관리자는 하나 이상의 PodSecurityPolicy 리소스를 생성해 앞에서 설명한 보안 관련 기능의 사용을 제한할 수 있다.
PodSecurityPolicy: 클러스터 수준 리소스. 사용자가 파드에서 사용할 수 있거나 사용할 수 없는 보안 관련 기능을 정의한다.

PodSecurityPolicy가 할 수 있는 작업
- 파드가 호스트의 IPC, PID 또는 네트워크 네임스페이스를 사용할 수 있는지 여부
- 파드가 바인딩할 수 있는 호스트 포트
- 컨테이너가 실행할 수 있는 사용자 ID
- priviledged 컨테이너가 있는 파드를 만들 수 있는지 여부
- 어떤 커널 기능이 허용되는지, 어떤 기능이 기본으로 추가되거나 혹은 항상 삭제되는지 여부
- 컨테이너가 사용할 수 있는 SELinux 레이블
- 컨테이너가 쓰기 가능한 루트 파일시스템을 사용할 수 있는지 여부
- 컨테이너가 실행할 수 있는 파일시스템 그룹
- 파드가 사용할 수 있는 볼륨 유형

### 각각의 사용자와 그룹에 다른 PodSecurityPolicies 할당

PodSecurityPolicy는 클러스터 수준의 리소스이므로 특정 네임스페이스를 지정하거나 적용할 수 없다.
다른 사용자에게 다른 정책을 할당하는 것은 RBAC(Role Based Access Control) 메커니즘으로 수행된다.
⇒ 클러스터롤 리소스를 만들고
이름으로 개별 정책을 지정해 필요한 만큼 많은 정책을 작성하고
개별 사용자 또는 그룹이 사용할 수 있도록

예제를 통해 이해해보자.

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  ...  
```

<img alt="kubectl-get-psp" width=600 src="https://user-images.githubusercontent.com/55703132/210813197-ff2cf679-f255-41e6-9b65-1c50e5661f41.jpeg" />

\- Alice: 권한이 없는 파드만 배포
\- Bob: 권한이 있는 파드도  배포

클러스터롤 만들기
```sh
$ kubectl create clusterrole psp-default --verb-use \
  --resource=podsecuritypolicies --resource-name=default
clusterrole "psp-default" created

$ kubectl create clusterrole psp-priviledged --verb-use \
  --resource=podsecuritypolicies --resource-name=priviledged
clusterrole "psp-priviledged" created
```

클러스터롤 바인딩
```sh
$ kubectl create clusterrolebinding psp-all-users \
  --clusterrole=psp-default --group=system:authenticated
clusterrolebinding "psp-all-users" created

$ kubectl create clusterrolebinding psp-bob \
  --clusterrole=psp-priviledged --group=bob
clusterrolebinding "psp-bob" created
```

<img width=600 src="https://user-images.githubusercontent.com/55703132/210817729-a2d9ceb9-0e82-41e8-b686-5b53c69eb8b2.jpg" />

<img width=600 src="https://user-images.githubusercontent.com/55703132/210817621-4c01c515-8a4e-426a-a1b5-3c78ddb89feb.png" />

## 파드 네트워크 격리

- 네임스페이스에서 네트워크 격리 사용

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
# 빈 파드 셀렉터는 동일 네임스페이스의 모든 파드와 매치된다.
```

- 네임스페이스의 일부 클라이언트 파드만 서버 파드에 연결하도록 허용

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-netpolicy
spec:
  podSelector:
    matchLabels:
      app: database
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webserver
    ports:
    - port: 5432
```

![그림13.4](https://user-images.githubusercontent.com/55703132/210919644-ae412b7e-2b2c-47f5-b931-4fd2f9f21ed1.jpeg)

\* 클라이언트 파드는 일반적으로 파드가 아닌 서비스로 서버 파드에 연결되는데, NetworkPolicy는 서비스로 연결할 때도 적용된다.

- 쿠버네티스 네임스페이스 간 네트워크 격리

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shoppingcart-netpolicy
spec:
  podSelector:
    matchLabels:
      app: shopping-cart
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tenant: manning
    ports:
    - port: 80
```

![그림13.5](https://user-images.githubusercontent.com/55703132/210920319-d08320b3-3595-43e4-9c22-0aa35855b61a.png)

- CIDR 표기법으로 격리

```yaml
    ingress:
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24
```

- 파드의 아웃바운드 트래픽 제한
egress 사용

```yaml
spec:
  podSelector:
    matchLabels:
      app: webserver
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: database
```
