### ISSUE TITLE
Chapter14. 파드의 컴퓨팅 리소스 관리

### ISSUE THREAD

**Issue by gimmizz** [data-tech-newbie/Kubernetes_In_Action#14]
> 파드의 예상 소비량과 최대 소비량을 설정하는 것은 매우 중요
> 

### 14.1 파드 컨테이너의 리소스 요청 : `requests`

- 파드를 생성할 때, 컨테이너 별로 리소스를 요청할 수 있다.
    - `requests` : 컨테이너가 필요로 하는 CPU, 메모리 양
    - `limit` : 컨테이너가 사용할 수 있는 엄격한 제한
- 파드의 requests와 limits 는 모든 컨테이너의 리소스 요청/제한의 합
```yaml
apiVersion: v1
        kind: Pod
        metadata:
          name: requests-pod
        spec:
          containers:
          - image: busybox
            command: ["dd", "if=/dev/zero", "of=/dev/null"]name: main
resources:
  requests:
    cpu: 200m     -> 하나의 CPU 코어 시간의 1/5
    memory: 10Mi
```
- 프로세스의 CPU 소비량 확인하기: `top`
    ```yaml
    $ kubectl exec -it requests-pod top
    Mem: 1288116K used, 760368K free, 9196K shrd, 25748K buff, 814840K cached
    CPU:  9.1% usr 42.1% sys  0.0% nic 48.4% idle  0.0% io  0.0% irq  0.2% sirq
    Load average: 0.79 0.52 0.29 2/481 10
    PID PPID USER STAT VSZ %VSZ CPU %CPU COMMAND
    1 0 root R 1192 0.0 1 50.2 dd if /dev/zero of /dev/null 7 0root R 1200 0.0 0 0.0top
    ```
    - 컨테이너가 파드 스펙에서 요청한 200m 코어 이상을 사용 중
        - `limit` 을 지정해야 하는 상황
- 리소스 요청을 지정하는 것이 파드 스케줄링에 어떤 영향을 미칠까?
    - 스케줄러가 노드에 파드를 스케줄링할 때 (각 개별 리소스가 얼마나 사용되는지 보지 않고,) 노드에 배포된 파드들의 **리소스 요청량**의 전체 합만 본다
    ![image](https://user-images.githubusercontent.com/69383392/214461261-fb404be3-0a6a-469e-801a-09ad77b8a773.png)
    - 스케줄러가 최적의 노드를 선택하는 과정
        - 파드에 맞지 않는 노드를 필터링
        - 우선순위 함수에 따라 지정
            - 요청된 리소스 양에 기반한 우선순위 함수
                - `LeastRequestedPriority` : 요청된 리소스가 낮은 노드 선호
                - `MostRequestedPriority` : 요청된 리소스가 많은 노드 선호
                    - ex) 최대한 적은 수의 노드를 사용하고자 하는 클라우드 인프라
- 노드의 용량 검사
    ```yaml
    $ kubectl describe nodes
    Name:       minikube
    ...
    Capacity:  # The overall capacity of the node
      cpu:           2
      memory:        2048484Ki
      pods:          110
    Allocatable:  # The resources allocatable to pods
      cpu:           2
      memory:        1946084Ki
      pods:          110
    ...
    ```
- 노드의 용량을 맞춰서 파드를 요청해도, 실행할 수 없는 경우
    - 위와 같은 노드에 아래 2개의 파드가 실행 중이라고 가정
        - 파드 A request: cpu(200m), memory(10Mi)
        - 파드 B request: cpu(800m), memory(20Mi)
        - total cpu request: 1000m = 1 core
    - 파드 1개 추가
        - 파드 C request: cpu(1), memory(20Mi)
    - request의 총합이 2코어이지만, 파드C 는 실행되지 않고 Pending
    - 이유?
        ```yaml
        $ kubectl describe node
        Name:
        ...
        Non-terminated Pods:
        minikube
        (7 in total)
               CPU Requ.   CPU Lim.  Mem Req.    Mem Lim.
               ----------  --------  ---------   --------
        Namespace    Name
        ---------    ----
        default      requests-pod    200m (10%)  0 (0%)    10Mi (0%)   0 (0%)
        410
        CHAPTER 14 Managing pods’ computational resources
        default      requests-pod-2  800m (40%)  0 (0%)    20Mi (1%)   0 (0%)
        kube-system  dflt-http-b...  10m (0%)    10m (0%)  20Mi (1%)   20Mi (1%)
          kube-system  kube-addon-...  5m (0%)     0 (0%)
          kube-system  kube-dns-26...  260m (13%)  0 (0%)
          kube-system  kubernetes-...  0 (0%)      0 (0%)
          kube-system  nginx-ingre...  0 (0%)      0 (0%)
        Allocated resources:
        50Mi (2%)   0 (0%)
        110Mi (5%)  170Mi (8%)
        (Total limits may be over 100 percent, i.e., overcommitted.)
        CPU Requests CPU Limits ------------ ---------- 1275m (63%) 10m (0%)
        Memory Requests Memory Limits
        --------------- -------------
        210Mi (11%)     190Mi (9%)
        ```
        - `kube-system` 네임스페이스에서 275m 를 추가로 사용
            - cf) kube-system namespace: 쿠버네티스 클러스터 구성에 필수적인 컴포넌트들과 설정값 등이 존재하는 네임스펭시ㅡ
    - 다른 리소스를 해제해야만 파드C 실행 가능
- CPU 요청이 CPU 시간 공유에 미치는 영향
    - **남은(미사용한) CPU 시간을 파드 간에 분배**하는 방식도 결정
    ![image](https://user-images.githubusercontent.com/69383392/214461333-0d32e167-6b92-4974-ad98-a5d34e37e80a.png)
- 사용자 정의 리소스의 정의와 요청
    - = Extended Resources
    - 방법
        1. 노드 오브젝트에 capacity 필드에 값을 추가, 리소스 이름을 설정
        2. 파드를 생성할 때 동일한 리소스 일므과 수량을 컨테이너 스펙의 resources.requests  에 정의
    - 사용예제) GPU 단위수 사용 설정

### 14.2 컨테이너에 사용 가능한 리소스 제한 : `limits`

- 리소스 제한의 필요성
    - CPU는 압축 가능한 리소스임에 반면, 메모리는 그렇지 않음
    - 노드에 있는 다른 모든 파드와 노드에 스케줄링되는 새 파드에 영향을 미칠 수 있음.
- 리소스 제한 설정 방법
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: limited-pod
    spec:
      containers:
      - image: busybox
        command: ["dd", "if=/dev/zero", "of=/dev/null"]
        name: main
        resources:
          limits:
             cpu: 1
             memory: 20Mi
    ```
    - 리소스 요청을 지정하지 않았으므로, 리소스 제한과 동일한 값으로 설정
- 리소스 제한 오버커밋
    - 노드에 있는 모든 파드의 리소스 제한 합계는 **노드 용량의 100%를 초과**할 수 있다    
    ![image](https://user-images.githubusercontent.com/69383392/214461377-5c87dbc2-99a1-4f6a-bd8d-073d12cbc1ff.png)
    - 예시 | [https://no-easy-dev.tistory.com/entry/쿠버네티스-Pod-자원관리](https://no-easy-dev.tistory.com/entry/%EC%BF%A0%EB%B2%84%EB%84%A4%ED%8B%B0%EC%8A%A4-Pod-%EC%9E%90%EC%9B%90%EA%B4%80%EB%A6%AC)
- 리소스 제한을 초과한다면?
    - CPU 사용률은 조절 가능
    - 메모리는, 제한보다 많은 메모리를 할당받으려 하면 프로세스가 종료된
        - `OOMKilled`
        - 메모리 제한 초과와 종료가 지속되면, 재시작 사이의 지연 시간을 증가시키며 재시작시킨다 = `CrashLoopBackOff` 상태
- 컨테이너의 애플리케이션이 제한을 바라보는 방법
    ```yaml
    $ kubectl exec -it limited-pod top
    Mem: 1450980K used, 597504K free, 22012K shrd, 65876K buff, 857552K cached CPU: 10.0% usr 40.0% sys 0.0% nic 50.0% idle 0.0% io 0.0% irq 0.0% sirq Load average: 0.17 1.19 2.47 4/503 10
    PID PPID USER STAT VSZ %VSZ CPU %CPU COMMAND
    1 0 root R 1192 0.0 1 49.9 dd if /dev/zero of /dev/null 5 0root R 1196 0.0 0 0.0top
    ```
    - `used`, `free` 부분은 “노드” 관점에서 표시
    - 컨테이너는 항상 컨테이너 메모리가 아닌 **노드 메모리**를 본다.
        - OOMKilled 될 가능성이 높음.
    - 컨테이너는 또한 **노드의 모든 CPU 코어**를 본다.

### 14.3 파드 QoS 클래스 이해

- 오버커밋 상황에서 어떤 컨테이너를 종료해야 할까?
    - 파드 별 우선순위가 존재 = 3가지 `QoS` (Quality of Service) 클래스
    - 파드 컨테이너의 리소스 요청과 제한의 조합
- 3가지 QoS 클래스
    1. `BestEffort` 클래스: 아무런 리소스 요청과 제한이 없는 파드
        - 최하위 우선순위라 리소스 보장 X
    2. `Guaranteed` 클래스: 리소스 요청이 리소스 제한과 동일한 파드
        - 모든 컨테이너가 동일하게 리소스요청=리소스제한
        - 요청된 리소스의 양을 얻지만, 추가 리소스를 사용할 수 없다
            - requests = limits 이기 때문
    3. `Burstable` 클래스: 그 밖의 모든 파드
    ![image](https://user-images.githubusercontent.com/69383392/214461431-b36e8a8a-8a99-4a30-bbeb-4f2e5afea4f5.png)
- BestEffort < Burstable < Guaranteed 우선순위이므로, 우선순위가 작은 파드부터 종료된다.
- 동일한 QoS 클래스라면?
    - 실행 중인 각 프로세스는 OOM 점수를 갖고, 가장 높은 점수의 프로세스가 종료
    - 동일한 QoS 클래스라면, **요청된 메모리의 비율이 높은 컨테이너를 종료**
![image](https://user-images.githubusercontent.com/69383392/214461468-97764c1a-0d58-4f1f-b418-94234c4864e0.png)

### 14.4 네임스페이스별 파드에 대한 기본 요청과 제한 설정 : `LimitRange`
- 역할
    - 컨테이너의 각 리소스에 최소/최대 제한을 지정
    - 리소스 요청을 명시적으로 지정하지 않은 컨테이너의 기본 리소스 요청을 지정
    ![image](https://user-images.githubusercontent.com/69383392/214461492-be8014d2-1621-43ec-8870-43807db09996.png)
- LimitRange 플러그인이 LimitRange 리소스에 설정된 정책을 실행
- LimitRange 오브젝트 생성
    ```yaml
    apiVersion: v1
    kind: LimitRange
    metadata:
      name: example
    spec:
      limits:
      - type: Pod  # 파드 단위 제한
        min:
          cpu: 50m
          memory: 5Mi
        max: cpu: 1
          memory: 1Gi
      - type: Container  # 컨테이너 단위 제한
        defaultRequest:  # 컨테이너 기본 요청
          cpu: 100m
          memory: 10Mi
        default:         # 컨테이너 기본 제한
          cpu: 200m
          memory: 100Mi
        min:
          cpu: 50m
          memory: 5Mi
        max:
          cpu: 1
          memory: 1Gi
        maxLimitRequestRatio:  # 각 리소스의 제한과 요청 간의 최대 비율
          cpu: 4
          memory: 10
      - type: PersistentVolumeClaim  ****************# 단일 PVC에서 요청 가능한 스토리지 양 제한****************
        min:
          storage: 1Gi
        max:
          storage: 10Gi
    ```
- 새 제한은 이후에 생성된 파드 및 PVC 에만 적용
- LimitRange 에서 허용하는 것보다 더 많은 CPU를 요청하는 파드를 만든다면?
    ```yaml
    $ kubectl create -f limits-pod-too-big.yaml
    Error from server (Forbidden): error when creating "limits-pod-too-big.yaml": pods "too-big" is forbidden: [
      maximum cpu usage per Pod is 1, but request is 2.,
      maximum cpu usage per Container is 1, but request is 2.]
    ```
    

### 14.5 네임스페이스의 사용 가능한 총 리소스 제한하기 : `ResourceQuota`

- 네임스페이스에서 사용 가능한 총 리소스 양을 제한
- ResourceQuota Admission Control 플러그인이 ResrouceQuota 리소스에 설정된 정책을 실행 =  생성 중인 파드가 리소스쿼터를 초과하는지 확인
    - ResourceQuota 오브젝트를 생성한 이후에 생성된 파드에만 영향
- ResourceQuota를 생성할 때, **LimitRange 오브젝트도 함께** 생성해야 한다
- 지정할 수 있는 쿼터 종류
    - CPU 및 메모리: 모든 파드의 리소스 요청과 제한의 총합에 적용
        - cf) LImitRange 는 개별 파드/컨테이너에 적용
        ![image](https://user-images.githubusercontent.com/69383392/214461549-55e97a17-cce4-41d5-a54a-7056c729ab25.png)
        ```yaml
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: cpu-and-mem
        spec:
          hard:
           requests.cpu: 400m
           requests.memory: 200Mi
           limits.cpu: 600m
           limits.memory: 500Mi
        ```
    - Persistent Storage
        - 모든 PVC가 요청할 수 있는 스토리지의 전체 용량
        - 특정 스토리지 클래스에 동적 프로비저닝된 퍼시스턴트 볼륨에 대한 제한도 가능
            - ex. SSD 스토리지 클래스에서 요청 가능한 SSD 스토리지 총 용량
            - ex. standard 스토리지 클래스에서 요청 가능한 HDD 스토리지 총 용량
        ```yaml
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: storage
        spec:
          hard:
          requests.storage: 500Gi
          ssd.storageclass.storage.k8s.io/requests.storage: 300Gi
          standard.storageclass.storage.k8s.io/requests.storage: 1Ti
        ```
    - 생성 가능한 오브젝트 수 제한
        - 현재는 Replicaset, Deployment에 대해서도 오브젝트 수 제한 가능
        ```yaml
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: objects
        spec:
          hard:
            pods: 10
            replicationcontrollers: 5
            secrets: 10
            configmaps: 10
            persistentvolumeclaims: 4
            services: 5
            services.loadbalancers: 1
            services.nodeports: 2
            ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2
        ```
    - 특정 파드 상태나 QoS 클래스에 대한 쿼터 지정
        - 쿼터 범위를 제한할 수 있음
        - BestEffort, NotBestEffort
        - Terminating, NotTerminating
            - 실패로 표시된 후 종료되기 전, 시작시간을 기준으로 노드에서 활성화되도록 허용하는 시간(초) = `activeDeadlineSeconds` 기준
        ```yaml
        apiVersion: v1
           kind: ResourceQuota
           metadata:
             name: besteffort-notterminating-pods
           spec:
             scopes:
             - BestEffort
             - NotTerminating
             hard:
                pods: 4
        ```
        

### 14.6 파드 리소스 사용량 모니터링

- 리소스 요청과 제한의 적정 지점을 어떻게 찾아야 할까?
    - 컨테이너의 실제 리소스 사용량을 **모니터링**
- 실제 리소스 사용량 수집과 검색
    ![image](https://user-images.githubusercontent.com/69383392/214461580-e8f904f5-0c67-4075-9df0-63ffed442bf4.png)
    - 개별 수집 : `cAdvisor`
        - 노드에서 실행되는 개별 컨테이너와 노드 전체의 리소스 사용 데이터를 수집
        - Kubelet 자체에 이미 포함되어 있는 에이전트
    - 중앙에서 통계 수집 : `Heapster`, 현재는 metrics-server
        - 클러스터에 있는 모든 cAdvisor로부터 데이터를 수집해 한곳에 노출
        - 수동으로 활성화해야 하는 경우
            - ex) Minikube
                ```yaml
                $ minikube addons enable heapster
                heapster was successfully enabled
                ```
    - 검색 : `kubectl top` 명령어
        - 노드와 개별 파드의 “실제”, “현재" 리소스 사용량을 얻을 수 있다
        - 때때로 오류를 출력할 때도 있는데, 잠시 기다렸다가 재실행 하면 문제 X
- 기간별 리소스 사용량 통계 저장 및 분석
    - top 명령은 “현재” 리소스 사용량만 표시하지만, 기간별 집계가 필요하다면?
        - cAdvisor와 heapster 는 짧은 기간 동안의 리소스 사용량 데이터만 보유
    - 통계 데이터 저장을 위한 : `InfluxDB`
        - 오픈소스 시계열 DB
    - 시각화와 분석을 위한 : `Grafana`
        - InfluxDB에 저장된 데이터를 시각화
        - 웹 콘솔 url을 찾고 싶다면?
            ```yaml
            # 일반적인 방법
            $ kubectl cluster-info
            ...
            monitoring-grafana is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube- system/services/monitoring-grafana
            
            # minikube를 사용한다면?
            $ minikube service monitoring-grafana -n kube-system
            Opening kubernetes service kube-system/monitoring-grafana in default
                 browser...
            ```
    - 분석 예시
        ![image](https://user-images.githubusercontent.com/69383392/214461640-b2a08de4-3eb3-4380-bd7f-30ecf189432d.png)
