### ISSUE TITLE
20220713

### ISSUE THREAD

**Issue by matteblack9** [data-tech-newbie/Kubernetes_In_Action#3]
### 파드란?
- 컨테이너 그룹.
- 쿠버네티스의 기본 빌딩 블록
<img width="841" alt="image" src="https://user-images.githubusercontent.com/23276899/178546242-3222d926-49df-44ee-b971-a7c23ae8e15e.png">

### 파드 특
- Pod는 Node 안에 한정해서 생성됨
![image](https://user-images.githubusercontent.com/23276899/178546005-cbef2586-8007-4b98-a761-61f5c6d9eed7.png)
**왜 컨테이너 - Pod를 거쳐서 굳이 관리할까?** 
- 컨테이너는 단일 프로세스를 실행하는 것을 목적으로 설계했다.
   - 한 컨테이너에서 여러 프로세스 실행 시, 로그 관리가 어렵다.
   - 한 컨테이너에서 여러 프로세스 실행 시, 비정상 종료 프로세스에 대하여 자동 재시작 매커니즘을 만들기 어렵다.
- **서로 관련있는** 여러 프로세스에 대하여 한꺼번에 관리할 필요가 있기 때문에 새로운 상위 개념을 만든 것
- pod 내 모든 컨테이너는 격리된 상태이지만, 동일한 IP 주소와 포트 공간을 공유한다. 
 -> 컨테이너 사이에 포트 번호가 겹치지 않도록 해야함
- 파일시스템은 서로 완전히 분리되어 있어서, Volume 개념을 사용해야한다.
- 쿠버네티스의 모든 파드는 플랫한 공유 네트워크 주소 공간에 상주
   - 모든 pod가 하나의 VM이라 생각하면 편하다. 

![image](https://user-images.githubusercontent.com/23276899/178550502-1bbb450a-68a1-414c-8c90-28d200eef80d.png)

### Pod 안에 그러면 컨테이너 구성은 어떻게?
** 시나리오: 프론트엔드 어플리케이션 서버와 백엔드 데이터베이스로 구성된 다중 계층 어플리케이션을 구성하고 싶다. **
- 같은 Pod에 모두 넣는다면
   - 같은 워커 노드에 모두 있기 때문에, 리소스를 낭비하게 됨.
   - 필요한 부분에 대해서만 개별적으로 확장이 불가하다.
- Pod를 서로 분리한다면
   - 노드를 여러 곳에서 쓰므로, 리소스를 적절히 잘 활용할 수 있다.
   - 클러스터 환경에서, 필요한 부분에 대해서 확장이 용이하다. 

### Pod 생성해보기
**시나리오 :  Front-end 쪽 코드를 작성했다 -> Nginx를 통해 웹서버를 띄우고 싶다.**

```
# -------------------------------------- #
# Run nginx                              #
# -------------------------------------- #
FROM reg.navercorp.com/base/centos7/nginx:1.12.1
COPY  ./nginx.conf conf/nginx.conf
WORKDIR /User/mateblack/mywebsite/
COPY index.html ./html

CMD ["nginx", "-g", "daemon off;"]
```

```
apiVersion: v1
kind: Pod
metadata:
  name: mywebsite
spec:
  containers:
    - image: registry.com/
      command: ["sleep", "infinity"]
      imagePullPolicy: IfNotPresent
      name: base-dev
      env:
        - name: NAMESPACE
          value: "matte-black-develop"
      resources:
        requests:
          memory: "16Gi"
          cpu: "8"
        limits:
          memory: "16Gi"
          cpu: "8"
      volumeMounts:
        - mountPath: /hello/world
          name: helloworld-keytab
  restartPolicy: Never
  volumes:
    - name: helloworld-keytab
      secret:
        secretName: helloworld-keytab
```
![image](https://user-images.githubusercontent.com/23276899/178551914-06bed2ae-8700-419f-91f9-a3a430317cca.png)

### 파드에 레이블 달기
**레이블이란?** 
- 어떤 파드가 어떤 것인지 쉽게 알 수 있도록 조직화하기 위해 임의의 기준을 정한 것.

![image](https://user-images.githubusercontent.com/23276899/178552807-73fe80b3-9852-4344-bdab-8e09dca7adc6.png)

![image](https://user-images.githubusercontent.com/23276899/178552982-2f975857-c3cc-4a90-9fa3-6c8fa5ad3ab0.png)

```
apiVersion: v1
kind: Pod
metadata:
  name: account-service
  labels:
    app: as
    rel: stable
spec:
  containers:
  - name: apache
    image: apache:1.14.2
    ports:
    - containerPort: 80
```

![image](https://user-images.githubusercontent.com/23276899/178634662-c454e6f6-1f27-4d1a-bdab-ac35b0ab9496.png)

#### 포트 포워딩
```
kubectl port-forward <pod 이름> 8080:9999
```

![image](https://user-images.githubusercontent.com/23276899/178634776-f7085df8-635f-48cd-8a92-4376fb361632.png)

- 레이블 Selector를 이용한 파드 선택
![image](https://user-images.githubusercontent.com/23276899/178635140-cf998f89-4c68-42f2-9427-23c0404a209e.png)

- 레이블과 Selector를 이용한 파드 스케줄링 제한
```
kubectl label node gke-kubia-85f6-node-0rrx gpu=true
kubectl label node gke-kubia-81f6-node-0rrx gpu=true
kubectl label node gke-kubia-75f6-node-0rrx gpu=false
kubectl label node gke-kubia-11f6-node-0rrx gpu=false
kubectl label node gke-kubia-75f6-node-0rrx gpu=true
kubectl label node gke-kubia-21f6-node-0rrx gpu=false
kubectl label node gke-kubia-75f6-node-0rrx gpu=true
kubectl label node gke-kubia-65f6-node-0rrx gpu=false
kubectl label node gke-kubia-35f6-node-0rrx gpu=true
```

```
apiVersion: V1
kind: Pod
metadata:
   name: kubia-gpu
spec:
   nodeSelector:
      gpu: "true"
   containers:
   - image: luksa/kubia
      name: kubia

```
### 네임스페이스를 사용한 리소스 그룹화

![image](https://user-images.githubusercontent.com/23276899/178554102-61139ae2-9de9-4df8-a65f-a3a3f1caffa8.png)

### 파드 중지와 제거
- pod 삭제
```
kubectl delete pod <pod 이름>
```
- Label Selector를 이용한 pod 삭제
![image](https://user-images.githubusercontent.com/23276899/178636544-6a2d4024-52a7-408b-914d-41dd64516b5f.png)

- Namespace를 이용한 pod 삭제
   - namespace 자체를 제거
```
kubectl delete ns custom-namespace
```

   - namespace 유지한 채 안에 있는 모든 파드 삭제 
```
kubectl delete pod --all
```
