### ISSUE TITLE
20220921

### ISSUE THREAD

**Issue by matteblack9** [data-tech-newbie/Kubernetes_In_Action#7]
# 컨피그맵과 시크릿: 어플리케이션 설정

## 어플리케이션에 설정값을 어떻게 전달할까?

**(secret과 configmap 만들고 어떻게 mount하는지만 알면 이 단원은 다 익힌 것이다)**

- 어플리케이션에 컨피그맵 설정하기
- 어플리케이션에 시크릿 설정하기

#### 어플리케이션 인수로 설정 전달
```Dockerfile
# luksa/fortune:args
...
ENTRYPOINT hello.sh
...
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fortune2s
spec:
  containers:
    - name: html-generator
      image: luksa/fortune:args
      args: ["2"]
...

```
#### 어플리케이션 환경변수로 설정 전달
```bash
#!/bin/bash

trap "exit" SIGINT
INTERVAL=$1
echo Configured to generate new fortune every $INTERVAL seconds
mkdir -p /var/htdocs

while:
do
    echo $(date) Writing fortune to /var/htdocs/index.html
    /usr/games/fortune > /var/htdocs/index.html
    sleep $INTERVAL
done

```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: fortune-blablah
      image: luksa/fortune:env
      env:
        - name: INTERVAL
          value: "30"
...

```

### 그런데 왜 저런식으로 환경변수 지정하는 것을 지양할까?
- 여러 환경에서 동일한 파드 정의를 재사용하기 위함
- 컨피그맵을 구성하면 value 대신 valueFrom으로 환경변숫값의 원본 소스로 사용할 수 있다.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myweb-env
spec:
  containers:
    - name: myweb
      image: ghcr.io/c1t1d0s7/go-myweb:alpine
      env:
        valueFrom:
          configMapKeyRef:
            name: myconfig
            key: INTERVAL
```
### 어플리케이션에 컨피그맵 설정하기

<img width="353" alt="image" src="https://user-images.githubusercontent.com/23276899/191318920-4fc61c2d-1f29-41fa-8270-28608ec65bab.png">

컨피그맵이라 부르는 별도 오브젝트로 분리할 수 있다.
키/값 쌍으로 구성된 맵이다.

**각각 다른 환경에 관해 동일한 이름으로 컨피그맵에 관한 여러 매니페스트를 유지할 수 있다. 
동일한 파드 정의를 사용하면서 각 환경에서 서로 다른 설정을 사용할 수 있다.**
(n** v** 예시를 통해 살펴보자)

<img width="575" alt="image" src="https://user-images.githubusercontent.com/23276899/191319508-a33598e5-0da0-4490-8df7-a08bc49d0e08.png">

#### 1. 컨피그맵 literal로 만들기
```
kubectl create configmap fortune-config --from-literal=sleep-interval=25 --from-literal=bar=baz --from-literal=one=two
```

```yaml
apiVersion: v1
data:
  bar: baz
  one: two
  sleep-interval: "25"
kind: ConfigMap
...
```
#### 2. 컨피그맵 파일로 만들기
```
kubectl create configmap my-config --from-file=helloworld
```
```
# helloworld 파일
 I'm fine thank you
```
```yaml
apiVersion: v1
data:
  helloworld: |
    I'm fine thank you
kind: ConfigMap
...
```
#### 3. 디렉터리에 있는 파일로 컨피그맵 생성

```
kubectl create configmap my-config --from-file=/path/to/dor
```

<img width="764" alt="image" src="https://user-images.githubusercontent.com/23276899/191321910-6ed5a51a-49e1-4603-a8f5-bfb7dcfa1e44.png">

#### 3. 환경변수 컨피그맵에서 가져오기
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  containers:
  - image: luksa/fortune:env
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
...
```

<img width="671" alt="image" src="https://user-images.githubusercontent.com/23276899/191322215-3719e62b-2569-43e2-910b-fb053bb4d98c.png">

**존재하지 않는 컨피그맵을 참조한다면?**
- 하나의 파드에서 여러개의 컨테이너를 생성할 때, 참조하는 컨테이너는 시작하는 데 실패하고, 참조 안하는 컨테이너는 정상적으로 시작.
- Configmap 생성하면 자동으로 실패한 컨테이너 다시 시작함.

#### 4. 컨피그맵 항목을 인자로 사용

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fortune-args-from-configmap
spec:
  containers:
  - image: luksa/fortune:args
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    args: ["$(INTERVAL)"]
...
```

#### 5. 컨피그맵 항목을 파일로 파운트

<img width="363" alt="image" src="https://user-images.githubusercontent.com/23276899/191323624-214c38d0-1e89-455d-996c-1c4b8e7a9dd3.png">

```
kubectl create configmap fortune-config --from-file=configmap-files
```

<img width="698" alt="image" src="https://user-images.githubusercontent.com/23276899/191323804-01b838a5-8b85-437f-8073-746996d36419.png">

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume
spec:
  containers:
  - image: luksa/fortune:env
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config ###########
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: config
      mountPath: /tmp/whole-fortune-config-volume
      readOnly: true
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
  - name: config ############
    configMap:
      name: fortune-config
```

<img width="619" alt="image" src="https://user-images.githubusercontent.com/23276899/191324071-1ff25bc6-cd6c-48fe-bfdd-2eec98b87434.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/23276899/191324372-a8ebe877-99ba-41c2-8c57-7ce25c28a286.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/23276899/191324639-cbed74a7-ebb2-48a3-8966-2c91b7969f26.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/23276899/191324681-27baf02d-1eb1-45dd-a7f1-99f48c184833.png">

#### 6. 컨피그맵 편집
```
kubectl edit configmap fortune-config
```

<img width="695" alt="image" src="https://user-images.githubusercontent.com/23276899/191325077-e8054c37-1708-4f58-9acf-f3a08fdfbcef.png">

### 어플리케이션에 시크릿 설정하기
- 컨테이너에 전달한 정보 중 보안을 유지할 필요가 있는 민감한 데이터들도 있다. 
   이를 컨피그맵 같은 것으로 하면, 다 노출이 되기 때문에, 시크릿이 등장했다.

#### 1. 컨피그맵과 시크릿 비교
<img width="711" alt="image" src="https://user-images.githubusercontent.com/23276899/191397344-3199ac10-4a21-465a-a750-99f45f2e1e87.png">
- 시크릿은 Base64 인코딩을 사용하는데, binary 값도 담을 수 있기 때문이다.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/23276899/191397565-bcb6e895-65ac-4896-80db-8bd7af2fb902.png">
- stringData 필드를 통해, Base64 인코딩되지 않는 일반텍스트(binary가 아닌)도 저장할 수 있다.

```yaml
# secret 매니페스트
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://my.api.com/api/v1"
    username: matteblack
    password: 1q2w3e4r 
```

```
kubectl apply -f ./secret.yaml
```

```yaml
apiVersion: v1
data:
  config.yaml: YXBpVXJsOiAiaHR0cHM6Ly9teS5hcGkuY29tL2FwaS92MSIKdXNlcm5hbWU6IHt7dXNlcm5hbWV9fQpwYXNzd29yZDoge3twYXNzd29yZH19
kind: Secret
metadata:
  creationTimestamp: 2018-11-15T20:40:59Z
  name: mysecret
  namespace: default
  resourceVersion: "7225"
  uid: c280ad2e-e916-11e8-98f2-025000000001
type: Opaque
```
#### 2. 시크릿을 파드에 마운트

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  containers:
  - image: luksa/fortune:env
    name: html-generator
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-config
      items:
      - key: my-nginx-config.conf
        path: https.conf
  - name: certs
    secret:
      secretName: fortune-https
```

<img width="707" alt="image" src="https://user-images.githubusercontent.com/23276899/191399732-af659a45-1a63-4936-bb83-d5fdb671f0e1.png">

- secret 볼륨은 시크릿 파일을 저장하는 데 인메모리 파일시스템을 사용한다. 
   민감한 데이터를 디스크에 저장해서 노출 시킬 가능성이 있기 때문이다. (프로세스 실행 시에만 유효하므로)

#### 3. 환경변수로 시크릿 항목 노출

<img width="714" alt="image" src="https://user-images.githubusercontent.com/23276899/191400908-3fac38d5-4a81-484d-8194-1d2b84a3bea7.png">
