### ISSUE TITLE
20221005 Chap.8

### ISSUE THREAD

**Issue by hyeriful** [data-tech-newbie/Kubernetes_In_Action#8]
# Chap.8 애플리케이션에서 파드 메타데이터와 그 외의 리소스에 액세스하기

- 이미 알고 있는 데이터 - 컨피그맵, 시크릿 볼륨 (chap.7)
- **실행 시점까지 알려지지 않은 데이터** (e.g. 파드의 IP, 호스트 노드 이름, 파드 자체의 이름)

## Downward API

파드와 해당 환경의 메타데이터를 전달할 수 있는 방법
- 환경변수
- (downwardAPI 볼륨 내에 있는) 파일

<img width=600 src="https://user-images.githubusercontent.com/55703132/193851039-b4a93558-fca0-4d0e-96f6-001b711bf022.png"/>

컨테이너에 전달할 수 있는 정보
- 파드의 이름
- 파드의 IP주소
- 파드가 속한 네임스페이스
- 파드가 실행 중인 노드의 이름
- 파드가 실행 중인 Service Account 이름 (12장에서)
- 각 컨테이너의 CPU와 메모리 요청 (14장에서)
- 각 컨테이너의 CPU와 메모리 제한 (14장에서)
- 파드의 레이블 (← downwardAPI 볼륨으로만 노출)
- 파드의 어노테이션 (← downwardAPI 볼륨으로만 노출)

### 환경변수로 메타데이터 노출하기

```yaml
apiVersion: v1
kind: Pod
metadata:
    name: downward
spec:
    containers:
    - name: main
...<생략>...
    env:
    - name: POD_NAME
      valueFrom:
          fieldRef:
              fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
          fieldRef:
              fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
          fieldRef:
              fieldPath: spec.nodeName
    - name: CONTAINER_CPU_REQUEST_MILLICORES
      valueFrom:
          resourceFieldRef:
              resource: requests.cpu
              divisor: 1m
```

### downwardAPI 볼륨에 파일로 메타데이터 전달

```yaml
apiVersion: v1
kind: Pod
metadata:
    name: downward
    labels:
        foo: bar
    annotations:
        key1: value1
spec:
    containers:
    - name: main
...<생략>...
    volumeMounts:
    - name: downward
      moundPath: /etc/downward
volumes:
- name: downward
   downwardAPI:
        items:
        - path: "podName"
           fieldRef:
               fieldPath: metadata.name
          - path: "labels"
           fieldRef:
               fieldPath: metadata.labels
          - path: "annotations"
           fieldRef:
               fieldPath: metadata.annotations
          - path: "containerCpuRequestMilliCores"
           resourceFieldRef:
               containerName: main
               resource: requests.cpu
               divisor: 1m
```

<img width=700 src="https://user-images.githubusercontent.com/55703132/193867658-f26acec6-b310-49d6-b364-b3628bdd1638.png"/>

#### ❓파드의 label과 annotation은 왜 환경변수로 설정할 수 없을까❓
**파드가 실행되는 동안 label과 annotation을 수정할 수 있기** 때문!!!
변경이 있을 때, 쿠버네티스가 이 값을 가지고 있는 파일을 업데이트해서 파드가 항상 최신 데이터를 볼 수 있도록 한다.
환경변숫값은 나중에 업데이트 불가하므로 최신상태를 유지할 수 없다.

## 쿠버네티스 API 서버와 통신

Downward API는 단지 파드 자체의 메타데이터와 모든 파드의 데이터 중 일부만 노출한다.
애플리케이션에서 클러스터에 정의된 다른 파드나 리소스에 관한 더 많은 정보가 필요한 경우 쿠버네티스 API 서버와 직접 통신해야 한다.

### 쿠버네티스 REST API

- api서버 url 얻기
- 인증을 직접 처리하는 대신 프록시로 서버와 통신하기

### 파드 내에서 API 서버와 통신하기

- API 서버의 위치를 찾아야 한다.
- API 서버와 통신하고 있는지 확인해야 한다.
- API 서버로 인증해야 한다.

### 앰배서더 컨테이너를 이용한 API 서버 통신 간소화

<img width=600 src="https://user-images.githubusercontent.com/55703132/193875611-a61fd973-ae7a-413b-b75a-ec8d40628164.png"/>

### 클라이언트 라이브러리를 사용해 API 서버와 통신
- 공식: [Golang 클라이언트](https://github.com/kubernetes/client-go), [Python](https://github.com/kubernetes-client/python)
- 이외에도 다른 여러 언어에 관한 사용자 제공 클라이언트 라이브러리가 있음
